site_name: NeoPipe Documentation
nav:
  - Home: index.md
  - Examples: 
      - Basic Use Pipeline: examples/basic_use_pipeline_model.md
      - Basic Use Task: examples/basic_use_task_module.md
      - Basic Use Result: examples/basic_use_result.md
  - API Reference:
      - Pipeline: api/pipeline.md
      - Result: api/result.md
      - Task: api/task.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png


markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings

